### PR TITLE
Feat/weight by category

### PR DESCRIPTION
**Pull request by nhatduy227**
1. Remove Increment and Decrement Component 
2. Add Auto adding to total weight 
Sharing Excess _ Food Rescue - Personal - Microsoft_ Edge 2021-06-02 10-55-53

### CODE REVIEW

**Review by lukeshinnn — COMMENTED** [review]
image

Small bug when you delete the default "0" from input box and leave it blank

**Review by lukeshinnn — CHANGES_REQUESTED** [review]
UI Change: align "Total Weight (lb)" on left side with food categories and total numerical weight in green on the right side under all category weights

**Comment by nhatduy227** [comment]
> image
> 
> Small bug when you delete the default "0" from input box and leave it blank

**Review by NikRamadhin — COMMENTED** [review]
Just a small issue: the last routes I tested is not showing at the top of the analytics table but rather at the 3rd place.

AnalyticsPic

**Review by NikRamadhin — APPROVED** [review]

**Review by lukeshinnn — APPROVED** [review]

**Pull request merged**
