### PR TITLE
Allow drivers to select stops in any order

### PR DESCRIPTION
**Pull request by ajh387**

### CODE REVIEW

**Review by nhatduy227 — COMMENTED** [review]
What we have currently is very nice! However, If we can disabled the deliveries until all the pick ups are completed that would make more senses

**Comment by ajh387** [comment]
> What we have currently is very nice! However, If we can disabled the deliveries until all the pick ups are completed that would make more senses

I could change the existing behavior of the application to do that, but in the current master branch it's already possible to schedule a pickup, a delivery, and then another pickup, and I'm not sure if it's really within the scope of this ticket to change that.

Capture

**Review by nhatduy227 — APPROVED** [review]
Yeah then I think my previous point is outside the scope of this ticket. LGTM !

**Review by tnguyen21 — APPROVED** [review]
LGTM

**Pull request merged**
