### PR TITLE
feat: Pickup Food and Weight Updates

### PR DESCRIPTION
**Pull request by kennyallex2**
- Removed the '0' placeholder used for the weight
- Added "Mixed Groceries" category
image

### CODE REVIEW

**Review by nhatduy227 — APPROVED** [review]
Straight forward changes. LGTM

**Comment by ryanmchenry2** [comment]
@tnguyen21 do we have clarity on preferences of `Mixed Groceries` vs. `Other`? I feel like maybe we should go with one or the other, but having both will likely clutter data.

**Comment by tnguyen21** [comment]
> @tnguyen21 do we have clarity on preferences of `Mixed Groceries` vs. `Other`? I feel like maybe we should go with one or the other, but having both will likely clutter data.

I'll reach out to Evan and clarify why he'd like this change.

**Review by tnguyen21 — APPROVED** [review]
After speaking with Evan he clarified that "Mixed Groceries" refer to boxes that have a mix of other categories, while "Other" are genuinely for miscellaneous items -- e.g. some organizations have given things like flowers in the past, which drivers would categorize as "Other"

I'm happy to pull in these changes given the context.

**Pull request merged**
